TebLocalPlannerROS:
  map_frame: map
  min_obstacle_dist: 0.005
  inflation_dist: 0.1

  acc_lim_theta: 0.8
  max_vel_theta: 0.8
  acc_lim_x: 0.5
  max_vel_x: 0.5
  max_vel_x_backwards: 0.5
  weight_kinematics_forward_drive: 100

  dt_ref: 0.1
  dt_hysteresis: 0.01
  max_global_plan_lookahead_dist: 3

  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4

  footprint_model:
    type: polygon
    vertices: [[-0.51,-0.35],[0.51,-0.35],[0.51,0.35],[-0.51,0.35]]

  costmap_converter_plugin: costmap_converter::CostmapToLinesDBSRANSAC
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5
  
  costmap_converter:
    CostmapToLinesDBSRANSAC:
      cluster_max_distance: 0.5
      cluster_min_pts: 2
      cluster_max_pts: 50
      ransac_inlier_distance: 0.02
      ransac_min_inliers: 10
      ransac_no_iterations: 10000
      ransac_remainig_outliers: 1
      ransac_convert_outlier_pts: false
      ransac_filter_remaining_outlier_pts: false
      convex_hull_min_pt_separation: 0.1
