robot_base_frame: base_footprint
footprint: [[-0.395, -0.25], [0.395, -0.25], [0.395, 0.25], [-0.395, 0.25]]
publish_frequency: 30

obstacles:
  observation_sources: left_front_rplidar_scan right_back_rplidar_scan
  track_unknown_space: true
  obstacle_range: 4.5
  raytrace_range: 5

  left_front_rplidar_scan:
    data_type: LaserScan
    expected_update_rate: 0
    clearing: true
    marking: true

  right_back_rplidar_scan:
    data_type: LaserScan
    expected_update_rate: 0
    clearing: true
    marking: true