TebLocalPlannerROS:
  map_frame: jeeves/map_nn0
  min_obstacle_dist: 0.2
  inflation_dist: 0.6

  acc_lim_theta: 0.5
  max_vel_theta: 0.5
  acc_lim_x: 0.3
  max_vel_x: 0.3
  max_vel_x_backwards: 0.3
  weight_kinematics_forward_drive: 1000

  footprint_model:
    type: polygon
    vertices: [[-0.2,-0.35],[0.82,-0.35],[0.82,0.35],[-0.2,0.35]]

  costmap_converter_plugin: costmap_converter::CostmapToLinesDBSRANSAC
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5
