TebLocalPlannerROS:
  map_frame: map
  min_obstacle_dist: 0.2
  inflation_dist: 0.6

  footprint_model:
    type: polygon
    vertices: [[-0.395, -0.25], [0.395, -0.25], [0.395, 0.25], [-0.395, 0.25]]

  costmap_converter_plugin: 'costmap_converter::CostmapToLinesDBSRANSAC'
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5
