local_costmap:
  plugins:
    - {name: obstacles, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation, type: 'costmap_2d::InflationLayer'}

  rolling_window: true
  width: 6
  height: 6
  resolution: 0.05
