DWAPlannerROS:
  # robot config
  acc_lim_theta: 2
  acc_lim_trans: 1
  acc_lim_x: 1
  acc_lim_y: 0
  max_vel_theta: 1
  min_vel_theta: 0.1
  max_vel_trans: 0.4
  min_vel_trans: 0.1
  max_vel_x: 0.4
  min_vel_x: -0.4
  max_vel_y: 0
  min_vel_y: 0  

  # forward simulation
  sim_time: 4
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
