robot_base_frame: base_footprint
footprint: [[-0.7, -0.55], [0.7, -0.55], [0.7, 0.55], [-0.7, 0.55]]
publish_frequency: 1

obstacles:
  observation_sources: left_front_rplidar_scan right_back_rplidar_scan
  track_unknown_space: true
  max_obstacle_height: 2
  obstacle_range: 3
  raytrace_range: 3

  left_front_rplidar_scan:
    data_type: LaserScan
    expected_update_rate: 0
    clearing: true
    marking: true

  right_back_rplidar_scan:
    data_type: LaserScan
    expected_update_rate: 0
    clearing: true
    marking: true
